DNA_Strand = "ATAATCTTATACTCCCCAACCGGGAGAGACCTCCTGGCCTACGTCGCTCTCTTACACGTGTTCGGTCCCAAAGGAGTGACATCGTGGCGACCTGGGACTAAGCCTGCTCGACACTGTCGTCCCGTGGGACTATTCTTTGAGCTAGGAGTTATCCAGCCAATCGACGGAGTTGACTCTATCCGACCTAGTTTGGCGGTAACCTGCAAAGATATGTGGCCGGCGCATCCCTTTCAACTAGCCAGGTCGTCCGAGCGTATATATTGCCGCGTGTCGACCTCTCGCTCCCCATGTCAACTATGAAACCAATCCGGCGCTAACCTAGAATTACCATAAGGGATACAACCTTTATTGAAAGCCAGCGACTCGGCGCCCGATCCCTATATGATCCCACCCATGAGGCGTCAGTAACGGTTAACGAGCATTCGCGGTCACCCGTACGATTCCGAGTCCGTTAACTTCACCCTCCCGAGAGACACCCCCCTACGTTCTGAAGATTCGGCTACGTCGATCGGAATTCAGTTCGTAGCAACCTTTGTGTCAACCAGATGGGTGCTTCAGCTGCGTTGCTATAGCTGGCCGCTTACGTTACACCGTTACCTAACCCATGAATCCACCGTGTGCTGCTTTAATATCGTATTCTTTGCCTTCATATCCGAGATAGAACCCGACAACGCTGGCGGATGGTAATCCTCGGCGAATAACTAGTATGCATGTGGGCCGAGGACCAAGATTCGACGTCTTCACAAAACCTGACCAACGAGCTAACTTTGAACGTATCAGGAGCTGGAGTATGAGTGCAGCGAACACCTCTCTTTTCTGCCACGGTAGAATCGGACACCGGTAGAGGGTTGGTTACTGCACAAAGCATACATTCATGAGAACAGTAGAGAGTTCTGG"
Reversed_Strand = DNA_Strand[::-1]
Complement_Strand = ""
s = len(Reversed_Strand)
i = 0
while i < s:
    if(Reversed_Strand[i] == 'A'):
        Complement_Strand += "T"
    if(Reversed_Strand[i] == 'T'):
        Complement_Strand += "A"
    if(Reversed_Strand[i] == "C"):
        Complement_Strand += "G"
    if(Reversed_Strand[i] == "G"):
        Complement_Strand += "C"
    i+=1
print(Complement_Strand)
