DNA_Strand = "ACCAAAAGACGCGCATCATCGGGATTGTGACGAAGAGGATGTTTGATCGACGAAGGTGGGACGGTTATGAACGATGATCGCCGTATGAAGGGGCTACACACGAATTCTGTCACGGCAATATATAGAGTTAATAGTCTACAGTTAAGGATGTCGAGTGGTTGACGCGGGGTCTGTTTGGTAATTTAATGACTTGAGCTATGATTGATCGCACGGGCATGCTTGGTTCGAGGGAAAGAGAAGTCAGATAGGGGTCGTGTACTGACACTAGGTTTCGGACACACGGTGTTTTTCAGCACAACATGGCTGGTTCGGCAGTACGGTCGTGGTGCATTCCTGAGTATTACGCTTTAAGCATACTACGGGTAAAAAGAATAGGCTATCGTGCACTAAGTCGGTCCATTTTATCAATCGAGGTGTCCTCGAATTGTCTGACCAAGGGCTAGGCGGCCGAGACACTTTGTATCAAGTGTTTCCGCTTCAGCATTAGTCAACCAGCCACCTCGCCTAGTTTCAGGTCCGCACTGCCTGAAGGTATCAGAAATTCTTGCAACTCAACAATGTCAAAGCGGGAGTTCATTGGTCGAACCCGATAGAACGATGGGTTCTCGCGCTTTAGTCCCCTCTACTTCGAGCCTACTTGCATGAAATGAAGAGCCTTTAAGGGAGAAGGGATGTTGTCTAAGTTATTAATATGAATAAGTTACTGCCACCTCTACATTAGTGGGACTCATCCGTCGGAACGAGGGATTGCAGTCGATTTGTAACGCCTACGGTTTCTTGCGCCTCCCGCATTCCTCGATGGGGATT"
s = len(DNA_Strand)
i = 0
A_count = 0
T_count = 0
G_count = 0
C_count = 0
while i < s:
    if(DNA_Strand[i] == 'A'):
        A_count+=1
    elif(DNA_Strand[i] == 'T'):
        T_count+=1
    elif(DNA_Strand[i] == 'G'):
        G_count+=1
    elif(DNA_Strand[i] == 'C'):
        C_count+=1
    i+=1
print(A_count)
print(C_count)
print(G_count)
print(T_count)
